/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerMenuSaldo;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Abdullah Azzam
 */
public class MenuSaldo extends javax.swing.JFrame {

    /**
     * Creates new form MenuSaldo
     */
    public MenuSaldo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuSaldo = new javax.swing.JLabel();
        jSaldoSukarela = new javax.swing.JButton();
        jSaldoWajib = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));

        jMenuSaldo.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jMenuSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuSaldo.setText("Menu Saldo");

        jSaldoSukarela.setText("Saldo Sukarela");
        jSaldoSukarela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaldoSukarelaActionPerformed(evt);
            }
        });

        jSaldoWajib.setText("Saldo Wajib");
        jSaldoWajib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaldoWajibActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jMenuSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addGap(144, 144, 144))
            .addGroup(layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSaldoSukarela, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSaldoWajib, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jMenuSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSaldoWajib, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jSaldoSukarela, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSaldoSukarelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaldoSukarelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSaldoSukarelaActionPerformed

    private void jSaldoWajibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaldoWajibActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSaldoWajibActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jMenuSaldo;
    private javax.swing.JButton jSaldoSukarela;
    private javax.swing.JButton jSaldoWajib;
    // End of variables declaration//GEN-END:variables

    //action listener
    public void addActionListener(ActionListener e) {
        jSaldoWajib.addActionListener(e);
        jSaldoSukarela.addActionListener(e);
    }
    
    
    //menu saldo
    public JButton getjSaldoWajib() {
        return jSaldoWajib;
    }

    public JButton getjSaldoSukarela() {
        return jSaldoSukarela;
    }
}
