/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerMenyimpanSimpanan_s;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Abdullah Azzam
 */
public class MenyimpanSimpanan_s extends javax.swing.JFrame {

    /**
     * Creates new form MenyimpanSimpanan_s
     */
    public MenyimpanSimpanan_s() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuSimpanan_s = new javax.swing.JLabel();
        jJumlahSimpanan_s = new javax.swing.JLabel();
        jjumlahUang_s = new javax.swing.JTextField();
        jtglMenyimpan_s = new javax.swing.JLabel();
        jSubmit_s = new javax.swing.JButton();
        TglMenyimpan_s = new datechooser.beans.DateChooserCombo();
        StatusSimpanan_s = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuSimpanan_s.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jMenuSimpanan_s.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuSimpanan_s.setText("Menu Menyimpan Simpanan Sukarela");

        jJumlahSimpanan_s.setText("Jumlah Simpanan");

        jjumlahUang_s.setText("Rp.");

        jtglMenyimpan_s.setText("Tanggal Menyimpan");

        jSubmit_s.setText("Submit");
        jSubmit_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubmit_sActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSubmit_s)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtglMenyimpan_s)
                                .addComponent(jjumlahUang_s, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jJumlahSimpanan_s)
                                .addComponent(jMenuSimpanan_s, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TglMenyimpan_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(StatusSimpanan_s, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jMenuSimpanan_s, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jJumlahSimpanan_s)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jjumlahUang_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jtglMenyimpan_s)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TglMenyimpan_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jSubmit_s)
                .addGap(18, 18, 18)
                .addComponent(StatusSimpanan_s, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSubmit_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubmit_sActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSubmit_sActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel StatusSimpanan_s;
    private datechooser.beans.DateChooserCombo TglMenyimpan_s;
    private javax.swing.JLabel jJumlahSimpanan_s;
    private javax.swing.JLabel jMenuSimpanan_s;
    private javax.swing.JButton jSubmit_s;
    private javax.swing.JTextField jjumlahUang_s;
    private javax.swing.JLabel jtglMenyimpan_s;
    // End of variables declaration//GEN-END:variables

    public void addActionListener(ActionListener e) {
         jSubmit_s.addActionListener(e);
    }

    public JButton getjSubmit_s() {
        return jSubmit_s;
    }

    public String getjjumlahUang_s() {
        return jjumlahUang_s.getText();
    }

    public String getTglMenyimpan_s() {
        return TglMenyimpan_s.getText();
    }

    public void ResetView() {
        jjumlahUang_s.setText("Rp.");
        TglMenyimpan_s.setText("dd/mm/yyyy");
    }

    public void setStatusSimpanan_s(String StatusSimpanan_s) {
        this.StatusSimpanan_s.setText(StatusSimpanan_s);
    }

}
