/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerSimpananSukarela;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Abdullah Azzam
 */
public class SimpananSukarela extends javax.swing.JFrame {

    /**
     * Creates new form SimpananSukarela
     */
    public SimpananSukarela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuSimpanan_s = new javax.swing.JLabel();
        jPenarikan_s = new javax.swing.JButton();
        jMenyimpan_s = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 411));

        jMenuSimpanan_s.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jMenuSimpanan_s.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuSimpanan_s.setText("Menu Simpanan Sukarela");

        jPenarikan_s.setText("Penarikan");
        jPenarikan_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPenarikan_sActionPerformed(evt);
            }
        });

        jMenyimpan_s.setText("Menyimpan");
        jMenyimpan_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenyimpan_sActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jMenuSimpanan_s, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPenarikan_s, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMenyimpan_s, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jMenuSimpanan_s, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jMenyimpan_s, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPenarikan_s, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPenarikan_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPenarikan_sActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPenarikan_sActionPerformed

    private void jMenyimpan_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenyimpan_sActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenyimpan_sActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jMenuSimpanan_s;
    private javax.swing.JButton jMenyimpan_s;
    private javax.swing.JButton jPenarikan_s;
    // End of variables declaration//GEN-END:variables

    
    //action listener
    public void addActionListener(ActionListener e) {
        jMenyimpan_s.addActionListener(e);
        jPenarikan_s.addActionListener(e);
    }

    
    //menu simpanan sukarela
    public JButton getjPenarikan_s() {
        return jPenarikan_s;
    }

    public JButton getjMenyimpan_s() {
        return jMenyimpan_s;
    }
}
