/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Abdullah Azzam
 */
public class SimpananWajib extends javax.swing.JFrame {

    /**
     * Creates new form SimpananWajib
     */
    public SimpananWajib() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuSimpanan_w = new javax.swing.JLabel();
        jjumlahSimpanan_w = new javax.swing.JLabel();
        jtglSimpanan_w = new javax.swing.JLabel();
        jSubmit_w = new javax.swing.JButton();
        jJumlahuang_w = new javax.swing.JTextField();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 411));

        jMenuSimpanan_w.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jMenuSimpanan_w.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuSimpanan_w.setText("Menu Simpanan Wajib");

        jjumlahSimpanan_w.setText("Jumlah Simpanan");

        jtglSimpanan_w.setText("Tanggal Simpanan");

        jSubmit_w.setText("Submit");
        jSubmit_w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubmit_wActionPerformed(evt);
            }
        });

        jJumlahuang_w.setText("Rp");
        jJumlahuang_w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jJumlahuang_wActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSubmit_w)
                .addGap(143, 143, 143))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtglSimpanan_w)
                            .addComponent(jjumlahSimpanan_w)
                            .addComponent(jJumlahuang_w, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jMenuSimpanan_w, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jMenuSimpanan_w, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jjumlahSimpanan_w)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jJumlahuang_w, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jtglSimpanan_w)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jSubmit_w)
                .addGap(107, 107, 107))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSubmit_wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubmit_wActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSubmit_wActionPerformed

    private void jJumlahuang_wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jJumlahuang_wActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jJumlahuang_wActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JTextField jJumlahuang_w;
    private javax.swing.JLabel jMenuSimpanan_w;
    private javax.swing.JButton jSubmit_w;
    private javax.swing.JLabel jjumlahSimpanan_w;
    private javax.swing.JLabel jtglSimpanan_w;
    // End of variables declaration//GEN-END:variables
}
